### ISSUE TITLE
Why there are only 11 subjects found in the leaderboards instead of 13?

### ISSUE THREAD

**Issue by zhimin-z** [llmeval/llmeval-3#1]
![image](https://github.com/llmeval/llmeval-1/assets/8592144/2fbcd4fe-59c4-4392-aca1-985c213e48f0)
![image](https://github.com/llmeval/llmeval-3/assets/8592144/cdce6b80-c4da-4958-8596-62fcab18e1d6)

**Comment by KongLongGeFDU** [comment]
为了方便模型间的横向比较，我们目前在13个学科内选择了10个学科作为测试学科。如果申请评测的模型需要测试全13类题型，我们也会提供支持。

**Comment by zhimin-z** [comment]
> 为了方便模型间的横向比较，我们目前在13个学科内选择了10个学科作为测试学科。如果申请评测的模型需要测试全13类题型，我们也会提供支持。

Thanks for your reply. But this should be specified clearly or it is hard to understand why this mismatch happens...
