### ISSUE TITLE
Seemingly redundant leaderboards?

### ISSUE THREAD

**Issue by zhimin-z** [llmeval/llmeval-3#3]
![image](https://github.com/llmeval/llmeval-3/assets/8592144/06d3d69a-1a1f-4347-a103-ce153f83050f)
![image](https://github.com/llmeval/llmeval-3/assets/8592144/e8f1602e-9e96-497b-8311-900f9a1c0f56)
![image](https://github.com/llmeval/llmeval-3/assets/8592144/680e3994-bd1f-4955-83ef-605eb54d1694)
![image](https://github.com/llmeval/llmeval-3/assets/8592144/a21e894a-92a2-4957-90f2-0566fa1bd70a)
![image](https://github.com/llmeval/llmeval-3/assets/8592144/2e055e9b-cb9f-4cdb-9b53-0f8ef7840ece)
![image](https://github.com/llmeval/llmeval-3/assets/8592144/fb550c83-398c-4896-9d89-4f7ae458827f)
Why seemingly duplicate leaderboards? Hope for an easy version of differentiation...
Check http://llmeval.com and https://github.com/llmeval/llmeval-3/blob/main/README.md

@qzhangFDU @Shichun-Liu @KongLongGeFDU

**Comment by Shichun-Liu** [comment]
您好！您看到的两个类似的排行榜是在不同的评测模型上完成的（分别是gpt4-4-1106以及gpt-4-0613），所以是两个不同的排行榜。我们在进行该工作是正值gpt4-4-1106-preview模型发布，于是我们进行了补测。为了避免歧义，我们决定撤下一个排行榜，只保留gpt-4-1106版本的排行榜。
感谢您对于我们工作的关注！

Hello! The two similar leaderboards you see were completed on different evaluation models (specifically gpt4-4-1106 and gpt-4-0613), so they are two distinct leaderboards. We conducted this work just as the gpt4-4-1106-preview model was released, so we conducted additional testing. To avoid ambiguity, we have decided to remove one ranking and only keep the leaderboard for the gpt-4-1106 version.
Thank you for your interest in our work!
